"""
Pydantic schemas for data validation
Defines the structure of data entering and leaving the API
"""
from pydantic import BaseModel, EmailStr, Field
from typing import Optional
from config import LatencyMode


# ============================================
# User schemas
# ============================================

class UserBase(BaseModel):
    """Base schema with common fields"""
    name: str = Field(..., min_length=1, max_length=100, description="User's name")
    email: EmailStr = Field(... , description="User's email")
    role: str = Field(..., min_length=1, max_length=50, description="User's role")


class UserCreate(UserBase):
    """
    Schema to CREATE a user
    Inherits from UserBase (all fields required)
    """
    pass


class UserUpdate(BaseModel):
    """
    Schema to UPDATE a user
    All fields are optional (partial update)
    """
    name: Optional[str] = Field(None, min_length=1, max_length=100)
    email: Optional[EmailStr] = None
    role: Optional[str] = Field(None, min_length=1, max_length=50)


class User(UserBase):
    """
    Schema to RETURN a user
    Includes the ID (generated by the database)
    """
    id: int = Field(..., description="Unique user ID")
    
    class Config:
        from_attributes = True  # Allows conversion from SQLAlchemy model


# ============================================
# LATENCY SCHEMAS
# ============================================

class LatencyModeRequest(BaseModel):
    """
    Schema to change latency mode
    """
    mode: LatencyMode = Field(
        ..., 
        description="Latency mode to apply",
        example="MEDIUM_LATENCY"
    )


class LatencyStatus(BaseModel):
    """
    Schema to return current latency status
    """
    current_mode: LatencyMode = Field(... , description="Current latency mode")
    read_delay: float = Field(... , description="Delay in seconds for read operations (GET)")
    write_delay: float = Field(..., description="Delay in seconds for write operations (POST/PATCH/DELETE)")
    description: str = Field(..., description="Description of current mode")


class LatencyModesInfo(BaseModel):
    """
    Schema to return information about all available modes
    """
    current_mode: LatencyMode
    available_modes: dict = Field(... , description="Available modes with their configurations")
    
    class Config:
        json_schema_extra = {
            "example": {
                "current_mode": "NO_LATENCY",
                "available_modes": {
                    "NO_LATENCY": {
                        "read": 0.0,
                        "write": 0.0,
                        "description": "No latency"
                    },
                    "LOW_LATENCY": {
                        "read": 0.1,
                        "write": 0.15,
                        "description": "Low latency"
                    }
                }
            }
        }